config/routes.rb
Rails.application.routes.draw do
  resources :beers
  get 'my_controller/delete'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :description, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.number_field :note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Beers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beers.each do |beer| %>
      <tr>
        <td><%= beer.name %></td>
        <td><%= beer.description %></td>
        <td><%= beer.note %></td>
        <td><%= link_to 'Show', beer %></td>
        <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
        <td><%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer', new_beer_path %>

app/views/beers/new.html.erb
<h1>New Beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @beer.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @beer.description %>
</p>

<p>
  <strong>Note:</strong>
  <%= @beer.note %>
</p>

<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>INF4041</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>